// Code generated by protoc-gen-go. DO NOT EDIT.
// source: appliance.proto

package appliancepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TemperatureSample struct {
	Value                float32              `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	ObservedAt           *timestamp.Timestamp `protobuf:"bytes,2,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TemperatureSample) Reset()         { *m = TemperatureSample{} }
func (m *TemperatureSample) String() string { return proto.CompactTextString(m) }
func (*TemperatureSample) ProtoMessage()    {}
func (*TemperatureSample) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb8bec84a49a6ea7, []int{0}
}

func (m *TemperatureSample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemperatureSample.Unmarshal(m, b)
}
func (m *TemperatureSample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemperatureSample.Marshal(b, m, deterministic)
}
func (m *TemperatureSample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemperatureSample.Merge(m, src)
}
func (m *TemperatureSample) XXX_Size() int {
	return xxx_messageInfo_TemperatureSample.Size(m)
}
func (m *TemperatureSample) XXX_DiscardUnknown() {
	xxx_messageInfo_TemperatureSample.DiscardUnknown(m)
}

var xxx_messageInfo_TemperatureSample proto.InternalMessageInfo

func (m *TemperatureSample) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *TemperatureSample) GetObservedAt() *timestamp.Timestamp {
	if m != nil {
		return m.ObservedAt
	}
	return nil
}

type GetTemperatureHistoryRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTemperatureHistoryRequest) Reset()         { *m = GetTemperatureHistoryRequest{} }
func (m *GetTemperatureHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetTemperatureHistoryRequest) ProtoMessage()    {}
func (*GetTemperatureHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb8bec84a49a6ea7, []int{1}
}

func (m *GetTemperatureHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTemperatureHistoryRequest.Unmarshal(m, b)
}
func (m *GetTemperatureHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTemperatureHistoryRequest.Marshal(b, m, deterministic)
}
func (m *GetTemperatureHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTemperatureHistoryRequest.Merge(m, src)
}
func (m *GetTemperatureHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetTemperatureHistoryRequest.Size(m)
}
func (m *GetTemperatureHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTemperatureHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTemperatureHistoryRequest proto.InternalMessageInfo

type GetTemperatureHistoryResponse struct {
	Samples              []*TemperatureSample `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetTemperatureHistoryResponse) Reset()         { *m = GetTemperatureHistoryResponse{} }
func (m *GetTemperatureHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetTemperatureHistoryResponse) ProtoMessage()    {}
func (*GetTemperatureHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb8bec84a49a6ea7, []int{2}
}

func (m *GetTemperatureHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTemperatureHistoryResponse.Unmarshal(m, b)
}
func (m *GetTemperatureHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTemperatureHistoryResponse.Marshal(b, m, deterministic)
}
func (m *GetTemperatureHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTemperatureHistoryResponse.Merge(m, src)
}
func (m *GetTemperatureHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetTemperatureHistoryResponse.Size(m)
}
func (m *GetTemperatureHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTemperatureHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTemperatureHistoryResponse proto.InternalMessageInfo

func (m *GetTemperatureHistoryResponse) GetSamples() []*TemperatureSample {
	if m != nil {
		return m.Samples
	}
	return nil
}

type GetCurrentTemperatureRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCurrentTemperatureRequest) Reset()         { *m = GetCurrentTemperatureRequest{} }
func (m *GetCurrentTemperatureRequest) String() string { return proto.CompactTextString(m) }
func (*GetCurrentTemperatureRequest) ProtoMessage()    {}
func (*GetCurrentTemperatureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb8bec84a49a6ea7, []int{3}
}

func (m *GetCurrentTemperatureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCurrentTemperatureRequest.Unmarshal(m, b)
}
func (m *GetCurrentTemperatureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCurrentTemperatureRequest.Marshal(b, m, deterministic)
}
func (m *GetCurrentTemperatureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCurrentTemperatureRequest.Merge(m, src)
}
func (m *GetCurrentTemperatureRequest) XXX_Size() int {
	return xxx_messageInfo_GetCurrentTemperatureRequest.Size(m)
}
func (m *GetCurrentTemperatureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCurrentTemperatureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCurrentTemperatureRequest proto.InternalMessageInfo

type GetCurrentTemperatureResponse struct {
	Sample               *TemperatureSample `protobuf:"bytes,1,opt,name=sample,proto3" json:"sample,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetCurrentTemperatureResponse) Reset()         { *m = GetCurrentTemperatureResponse{} }
func (m *GetCurrentTemperatureResponse) String() string { return proto.CompactTextString(m) }
func (*GetCurrentTemperatureResponse) ProtoMessage()    {}
func (*GetCurrentTemperatureResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb8bec84a49a6ea7, []int{4}
}

func (m *GetCurrentTemperatureResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCurrentTemperatureResponse.Unmarshal(m, b)
}
func (m *GetCurrentTemperatureResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCurrentTemperatureResponse.Marshal(b, m, deterministic)
}
func (m *GetCurrentTemperatureResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCurrentTemperatureResponse.Merge(m, src)
}
func (m *GetCurrentTemperatureResponse) XXX_Size() int {
	return xxx_messageInfo_GetCurrentTemperatureResponse.Size(m)
}
func (m *GetCurrentTemperatureResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCurrentTemperatureResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCurrentTemperatureResponse proto.InternalMessageInfo

func (m *GetCurrentTemperatureResponse) GetSample() *TemperatureSample {
	if m != nil {
		return m.Sample
	}
	return nil
}

type GetTargetTemperatureRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTargetTemperatureRequest) Reset()         { *m = GetTargetTemperatureRequest{} }
func (m *GetTargetTemperatureRequest) String() string { return proto.CompactTextString(m) }
func (*GetTargetTemperatureRequest) ProtoMessage()    {}
func (*GetTargetTemperatureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb8bec84a49a6ea7, []int{5}
}

func (m *GetTargetTemperatureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTargetTemperatureRequest.Unmarshal(m, b)
}
func (m *GetTargetTemperatureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTargetTemperatureRequest.Marshal(b, m, deterministic)
}
func (m *GetTargetTemperatureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTargetTemperatureRequest.Merge(m, src)
}
func (m *GetTargetTemperatureRequest) XXX_Size() int {
	return xxx_messageInfo_GetTargetTemperatureRequest.Size(m)
}
func (m *GetTargetTemperatureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTargetTemperatureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTargetTemperatureRequest proto.InternalMessageInfo

type GetTargetTemperatureResponse struct {
	Temperature          float32              `protobuf:"fixed32,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	SetAt                *timestamp.Timestamp `protobuf:"bytes,2,opt,name=set_at,json=setAt,proto3" json:"set_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetTargetTemperatureResponse) Reset()         { *m = GetTargetTemperatureResponse{} }
func (m *GetTargetTemperatureResponse) String() string { return proto.CompactTextString(m) }
func (*GetTargetTemperatureResponse) ProtoMessage()    {}
func (*GetTargetTemperatureResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb8bec84a49a6ea7, []int{6}
}

func (m *GetTargetTemperatureResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTargetTemperatureResponse.Unmarshal(m, b)
}
func (m *GetTargetTemperatureResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTargetTemperatureResponse.Marshal(b, m, deterministic)
}
func (m *GetTargetTemperatureResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTargetTemperatureResponse.Merge(m, src)
}
func (m *GetTargetTemperatureResponse) XXX_Size() int {
	return xxx_messageInfo_GetTargetTemperatureResponse.Size(m)
}
func (m *GetTargetTemperatureResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTargetTemperatureResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTargetTemperatureResponse proto.InternalMessageInfo

func (m *GetTargetTemperatureResponse) GetTemperature() float32 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

func (m *GetTargetTemperatureResponse) GetSetAt() *timestamp.Timestamp {
	if m != nil {
		return m.SetAt
	}
	return nil
}

type SetTargetTemperatureRequest struct {
	Temperature          float32  `protobuf:"fixed32,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetTargetTemperatureRequest) Reset()         { *m = SetTargetTemperatureRequest{} }
func (m *SetTargetTemperatureRequest) String() string { return proto.CompactTextString(m) }
func (*SetTargetTemperatureRequest) ProtoMessage()    {}
func (*SetTargetTemperatureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb8bec84a49a6ea7, []int{7}
}

func (m *SetTargetTemperatureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTargetTemperatureRequest.Unmarshal(m, b)
}
func (m *SetTargetTemperatureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTargetTemperatureRequest.Marshal(b, m, deterministic)
}
func (m *SetTargetTemperatureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTargetTemperatureRequest.Merge(m, src)
}
func (m *SetTargetTemperatureRequest) XXX_Size() int {
	return xxx_messageInfo_SetTargetTemperatureRequest.Size(m)
}
func (m *SetTargetTemperatureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTargetTemperatureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetTargetTemperatureRequest proto.InternalMessageInfo

func (m *SetTargetTemperatureRequest) GetTemperature() float32 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

type SetTargetTemperatureResponse struct {
	Temperature          float32              `protobuf:"fixed32,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	SetAt                *timestamp.Timestamp `protobuf:"bytes,2,opt,name=set_at,json=setAt,proto3" json:"set_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SetTargetTemperatureResponse) Reset()         { *m = SetTargetTemperatureResponse{} }
func (m *SetTargetTemperatureResponse) String() string { return proto.CompactTextString(m) }
func (*SetTargetTemperatureResponse) ProtoMessage()    {}
func (*SetTargetTemperatureResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb8bec84a49a6ea7, []int{8}
}

func (m *SetTargetTemperatureResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTargetTemperatureResponse.Unmarshal(m, b)
}
func (m *SetTargetTemperatureResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTargetTemperatureResponse.Marshal(b, m, deterministic)
}
func (m *SetTargetTemperatureResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTargetTemperatureResponse.Merge(m, src)
}
func (m *SetTargetTemperatureResponse) XXX_Size() int {
	return xxx_messageInfo_SetTargetTemperatureResponse.Size(m)
}
func (m *SetTargetTemperatureResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTargetTemperatureResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetTargetTemperatureResponse proto.InternalMessageInfo

func (m *SetTargetTemperatureResponse) GetTemperature() float32 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

func (m *SetTargetTemperatureResponse) GetSetAt() *timestamp.Timestamp {
	if m != nil {
		return m.SetAt
	}
	return nil
}

func init() {
	proto.RegisterType((*TemperatureSample)(nil), "appliancepb.TemperatureSample")
	proto.RegisterType((*GetTemperatureHistoryRequest)(nil), "appliancepb.GetTemperatureHistoryRequest")
	proto.RegisterType((*GetTemperatureHistoryResponse)(nil), "appliancepb.GetTemperatureHistoryResponse")
	proto.RegisterType((*GetCurrentTemperatureRequest)(nil), "appliancepb.GetCurrentTemperatureRequest")
	proto.RegisterType((*GetCurrentTemperatureResponse)(nil), "appliancepb.GetCurrentTemperatureResponse")
	proto.RegisterType((*GetTargetTemperatureRequest)(nil), "appliancepb.GetTargetTemperatureRequest")
	proto.RegisterType((*GetTargetTemperatureResponse)(nil), "appliancepb.GetTargetTemperatureResponse")
	proto.RegisterType((*SetTargetTemperatureRequest)(nil), "appliancepb.SetTargetTemperatureRequest")
	proto.RegisterType((*SetTargetTemperatureResponse)(nil), "appliancepb.SetTargetTemperatureResponse")
}

func init() {
	proto.RegisterFile("appliance.proto", fileDescriptor_cb8bec84a49a6ea7)
}

var fileDescriptor_cb8bec84a49a6ea7 = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x9b, 0x96, 0x56, 0x9c, 0x1c, 0xc4, 0xa5, 0x42, 0x49, 0x6d, 0x0d, 0x7b, 0x4a, 0x3d,
	0xa4, 0x58, 0x41, 0x04, 0x0f, 0x52, 0x3c, 0xe8, 0x39, 0x29, 0x88, 0x27, 0xd9, 0xe8, 0xb4, 0x14,
	0x92, 0xee, 0xba, 0xbb, 0x29, 0xf8, 0x21, 0xfd, 0x4e, 0xd2, 0xfc, 0xd1, 0x48, 0x92, 0x36, 0x27,
	0x8f, 0xd9, 0x79, 0xe4, 0xf7, 0x66, 0xde, 0x83, 0x13, 0x26, 0x44, 0xb8, 0x66, 0x9b, 0x37, 0x74,
	0x85, 0xe4, 0x9a, 0x13, 0xf3, 0xe7, 0x41, 0x04, 0xd6, 0xc5, 0x8a, 0xf3, 0x55, 0x88, 0xd3, 0x64,
	0x14, 0xc4, 0xcb, 0xa9, 0x5e, 0x47, 0xa8, 0x34, 0x8b, 0x44, 0xaa, 0xa6, 0x4b, 0x38, 0x5d, 0x60,
	0x24, 0x50, 0x32, 0x1d, 0x4b, 0xf4, 0x59, 0x24, 0x42, 0x24, 0x7d, 0xe8, 0x6e, 0x59, 0x18, 0xe3,
	0xc0, 0xb0, 0x0d, 0xa7, 0xed, 0xa5, 0x1f, 0xe4, 0x0e, 0x4c, 0x1e, 0x28, 0x94, 0x5b, 0x7c, 0x7f,
	0x65, 0x7a, 0xd0, 0xb6, 0x0d, 0xc7, 0x9c, 0x59, 0x6e, 0x4a, 0x70, 0x73, 0x82, 0xbb, 0xc8, 0x09,
	0x1e, 0xe4, 0xf2, 0xb9, 0xa6, 0x63, 0x38, 0x7f, 0x44, 0x5d, 0x40, 0x3d, 0xad, 0x95, 0xe6, 0xf2,
	0xd3, 0xc3, 0x8f, 0x18, 0x95, 0xa6, 0x2f, 0x30, 0xaa, 0x99, 0x2b, 0xc1, 0x37, 0x0a, 0xc9, 0x2d,
	0x1c, 0xa9, 0xc4, 0x9d, 0x1a, 0x18, 0x76, 0xc7, 0x31, 0x67, 0x63, 0xb7, 0xb0, 0xa8, 0x5b, 0x5a,
	0xc2, 0xcb, 0xe5, 0x19, 0xfa, 0x21, 0x96, 0x12, 0x37, 0x45, 0x42, 0x8e, 0x7e, 0x4e, 0xd0, 0x55,
	0xf3, 0x0c, 0x7d, 0x03, 0xbd, 0xf4, 0x5f, 0xc9, 0x3d, 0x0e, 0x93, 0x33, 0x35, 0x1d, 0xc1, 0x70,
	0xb7, 0x13, 0x93, 0x2b, 0xac, 0xe2, 0xaa, 0xf4, 0x24, 0xe5, 0x71, 0x86, 0xb5, 0xc1, 0xd4, 0xbf,
	0xcf, 0x59, 0x16, 0xc5, 0x27, 0x72, 0x05, 0x3d, 0x85, 0xba, 0x59, 0x18, 0x5d, 0x85, 0x7a, 0xae,
	0xe9, 0x3d, 0x0c, 0xfd, 0x7a, 0x4f, 0x87, 0x99, 0x3b, 0xd7, 0xfe, 0x7f, 0xbb, 0x9e, 0x7d, 0x75,
	0xe0, 0x78, 0x9e, 0xdf, 0x9c, 0x08, 0x38, 0xab, 0xec, 0x0a, 0x99, 0xfc, 0x09, 0x66, 0x5f, 0xdf,
	0xac, 0xcb, 0x26, 0xd2, 0x74, 0x25, 0xda, 0xca, 0x88, 0xe5, 0x8a, 0x94, 0x89, 0xb5, 0x35, 0x2b,
	0x13, 0xeb, 0x1b, 0x47, 0x5b, 0x24, 0x82, 0x7e, 0x55, 0x39, 0x88, 0x53, 0xf2, 0x5d, 0x13, 0xa5,
	0x35, 0x69, 0xa0, 0x2c, 0xe2, 0xfc, 0xc3, 0x38, 0xbf, 0x31, 0xce, 0xdf, 0x8b, 0x0b, 0x7a, 0x49,
	0xd4, 0xd7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x34, 0xed, 0x1c, 0x78, 0xbd, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ApplianceClient is the client API for Appliance service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApplianceClient interface {
	GetTemperatureHistory(ctx context.Context, in *GetTemperatureHistoryRequest, opts ...grpc.CallOption) (*GetTemperatureHistoryResponse, error)
	GetCurrentTemperature(ctx context.Context, in *GetCurrentTemperatureRequest, opts ...grpc.CallOption) (*GetCurrentTemperatureResponse, error)
	GetTargetTemperature(ctx context.Context, in *GetTargetTemperatureRequest, opts ...grpc.CallOption) (*GetTargetTemperatureResponse, error)
	SetTargetTemperature(ctx context.Context, in *SetTargetTemperatureRequest, opts ...grpc.CallOption) (*SetTargetTemperatureResponse, error)
}

type applianceClient struct {
	cc grpc.ClientConnInterface
}

func NewApplianceClient(cc grpc.ClientConnInterface) ApplianceClient {
	return &applianceClient{cc}
}

func (c *applianceClient) GetTemperatureHistory(ctx context.Context, in *GetTemperatureHistoryRequest, opts ...grpc.CallOption) (*GetTemperatureHistoryResponse, error) {
	out := new(GetTemperatureHistoryResponse)
	err := c.cc.Invoke(ctx, "/appliancepb.Appliance/GetTemperatureHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applianceClient) GetCurrentTemperature(ctx context.Context, in *GetCurrentTemperatureRequest, opts ...grpc.CallOption) (*GetCurrentTemperatureResponse, error) {
	out := new(GetCurrentTemperatureResponse)
	err := c.cc.Invoke(ctx, "/appliancepb.Appliance/GetCurrentTemperature", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applianceClient) GetTargetTemperature(ctx context.Context, in *GetTargetTemperatureRequest, opts ...grpc.CallOption) (*GetTargetTemperatureResponse, error) {
	out := new(GetTargetTemperatureResponse)
	err := c.cc.Invoke(ctx, "/appliancepb.Appliance/GetTargetTemperature", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applianceClient) SetTargetTemperature(ctx context.Context, in *SetTargetTemperatureRequest, opts ...grpc.CallOption) (*SetTargetTemperatureResponse, error) {
	out := new(SetTargetTemperatureResponse)
	err := c.cc.Invoke(ctx, "/appliancepb.Appliance/SetTargetTemperature", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApplianceServer is the server API for Appliance service.
type ApplianceServer interface {
	GetTemperatureHistory(context.Context, *GetTemperatureHistoryRequest) (*GetTemperatureHistoryResponse, error)
	GetCurrentTemperature(context.Context, *GetCurrentTemperatureRequest) (*GetCurrentTemperatureResponse, error)
	GetTargetTemperature(context.Context, *GetTargetTemperatureRequest) (*GetTargetTemperatureResponse, error)
	SetTargetTemperature(context.Context, *SetTargetTemperatureRequest) (*SetTargetTemperatureResponse, error)
}

// UnimplementedApplianceServer can be embedded to have forward compatible implementations.
type UnimplementedApplianceServer struct {
}

func (*UnimplementedApplianceServer) GetTemperatureHistory(ctx context.Context, req *GetTemperatureHistoryRequest) (*GetTemperatureHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTemperatureHistory not implemented")
}
func (*UnimplementedApplianceServer) GetCurrentTemperature(ctx context.Context, req *GetCurrentTemperatureRequest) (*GetCurrentTemperatureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentTemperature not implemented")
}
func (*UnimplementedApplianceServer) GetTargetTemperature(ctx context.Context, req *GetTargetTemperatureRequest) (*GetTargetTemperatureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTargetTemperature not implemented")
}
func (*UnimplementedApplianceServer) SetTargetTemperature(ctx context.Context, req *SetTargetTemperatureRequest) (*SetTargetTemperatureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTargetTemperature not implemented")
}

func RegisterApplianceServer(s *grpc.Server, srv ApplianceServer) {
	s.RegisterService(&_Appliance_serviceDesc, srv)
}

func _Appliance_GetTemperatureHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTemperatureHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplianceServer).GetTemperatureHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appliancepb.Appliance/GetTemperatureHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplianceServer).GetTemperatureHistory(ctx, req.(*GetTemperatureHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Appliance_GetCurrentTemperature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentTemperatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplianceServer).GetCurrentTemperature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appliancepb.Appliance/GetCurrentTemperature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplianceServer).GetCurrentTemperature(ctx, req.(*GetCurrentTemperatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Appliance_GetTargetTemperature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTargetTemperatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplianceServer).GetTargetTemperature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appliancepb.Appliance/GetTargetTemperature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplianceServer).GetTargetTemperature(ctx, req.(*GetTargetTemperatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Appliance_SetTargetTemperature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTargetTemperatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplianceServer).SetTargetTemperature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appliancepb.Appliance/SetTargetTemperature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplianceServer).SetTargetTemperature(ctx, req.(*SetTargetTemperatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Appliance_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appliancepb.Appliance",
	HandlerType: (*ApplianceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTemperatureHistory",
			Handler:    _Appliance_GetTemperatureHistory_Handler,
		},
		{
			MethodName: "GetCurrentTemperature",
			Handler:    _Appliance_GetCurrentTemperature_Handler,
		},
		{
			MethodName: "GetTargetTemperature",
			Handler:    _Appliance_GetTargetTemperature_Handler,
		},
		{
			MethodName: "SetTargetTemperature",
			Handler:    _Appliance_SetTargetTemperature_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "appliance.proto",
}
