# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: espresso.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65spresso.proto\x12\nespressopb\x1a\x1fgoogle/protobuf/timestamp.proto\"S\n\x11TemperatureSample\x12\r\n\x05value\x18\x01 \x01(\x02\x12/\n\x0bobserved_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"D\n\x12TemperatureHistory\x12.\n\x07samples\x18\x01 \x03(\x0b\x32\x1d.espressopb.TemperatureSample\"\x1a\n\x18TemperatureStreamRequest\"\x87\x01\n\x19TemperatureStreamResponse\x12\x31\n\x07history\x18\x01 \x01(\x0b\x32\x1e.espressopb.TemperatureHistoryH\x00\x12/\n\x06sample\x18\x02 \x01(\x0b\x32\x1d.espressopb.TemperatureSampleH\x00\x42\x06\n\x04\x64\x61ta\"\x19\n\x17GetConfigurationRequest\"q\n\rConfiguration\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\t\n\x01p\x18\x02 \x01(\x02\x12\t\n\x01i\x18\x03 \x01(\x02\x12\t\n\x01\x64\x18\x04 \x01(\x02\x12*\n\x06set_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\x8c\x02\n\x08\x45spresso\x12\x62\n\x11\x42oilerTemperature\x12$.espressopb.TemperatureStreamRequest\x1a%.espressopb.TemperatureStreamResponse0\x01\x12R\n\x10GetConfiguration\x12#.espressopb.GetConfigurationRequest\x1a\x19.espressopb.Configuration\x12H\n\x10SetConfiguration\x12\x19.espressopb.Configuration\x1a\x19.espressopb.Configurationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'espresso_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEMPERATURESAMPLE._serialized_start=63
  _TEMPERATURESAMPLE._serialized_end=146
  _TEMPERATUREHISTORY._serialized_start=148
  _TEMPERATUREHISTORY._serialized_end=216
  _TEMPERATURESTREAMREQUEST._serialized_start=218
  _TEMPERATURESTREAMREQUEST._serialized_end=244
  _TEMPERATURESTREAMRESPONSE._serialized_start=247
  _TEMPERATURESTREAMRESPONSE._serialized_end=382
  _GETCONFIGURATIONREQUEST._serialized_start=384
  _GETCONFIGURATIONREQUEST._serialized_end=409
  _CONFIGURATION._serialized_start=411
  _CONFIGURATION._serialized_end=524
  _ESPRESSO._serialized_start=527
  _ESPRESSO._serialized_end=795
# @@protoc_insertion_point(module_scope)
